version: '3.8'

services:
  node_backend:
    container_name: express-postgres
    image: express-postgres:0.0.5
    build:
      context: .
    ports: 
      - "5000:5000"
    environment:
      - PORT=5000
      - PSQL_DB=psql_db
      - PSQL_USER=ntesh
      - PSQL_PASSWORD=mypasswd47
      - PSQL_HOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: psql_db
    image: postgres:14
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=ntesh
      - POSTGRES_PASSWORD=mypasswd47
      - POSTGRES_DB=psql_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
 